[tool.black]
line-length = 120
exclude = '''
(
    .mypy_cache
    | .pytest_cache
    | .venv
)
'''

[tool.flake8]
ignore = "E203,W503,W504"
max-line-length = 150
exclude = "tests/*"
max-complexity = 10

[tool.isort]
profile = "black"